name: Deploy Backend to AWS EC2.

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Setup SSH Key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" | tr -d '\r' > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts

    - name: Deploy to EC2
      run: |
        ssh ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          cd ~/job-tracker-app/backend

          echo "Pulling latest changes..."
          git pull origin main

          echo "Installing dependencies..."
          npm install --production

          echo "Restarting backend server..."
          if pm2 list | grep -q backend; then
            pm2 restart backend
          else
            pm2 start index.js --name backend
          fi

          echo "Deployment completed!"
        EOF
